### ISSUE TITLE
[BUG] Presto Helm Chart Repo URL broken

### ISSUE THREAD

**Issue by dli5-sc** [prestodb/presto-helm-charts#2] opened 2023-11-07 23:01 UTC
## Describe the bug

`helm repo add presto https://prestodb.github.io/presto-helm-charts`

Error: looks like "https://prestodb.github.io/presto-helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://prestodb.github.io/presto-helm-charts/index.yaml : 404 Not Found

#### Steps to reproduce:
Run command `helm repo add presto https://prestodb.github.io/presto-helm-charts`

## Expected behavior
No error

## Current behavior
Error: looks like "https://prestodb.github.io/presto-helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://prestodb.github.io/presto-helm-charts/index.yaml : 404 Not Found

**Comment by dnskr** [comment] 2023-11-11 16:33
@dli5-sc Thank you for reporting the issue.
It's fixed now, so the following URLs are available again:
 - https://prestodb.github.io/presto-helm-charts
 - https://prestodb.github.io/presto-helm-charts/index.yaml

The root cause of the problem was in redirect (prestodb.github.io -> prestodb.io) enabled by Presto website repository workflow.

**Closed as completed by dnskr** 2023-11-11 16:33 UTC
Labels: bug
